export default [
  {
    id: 1,
    name: "Tayota",
    model: "Fortuiner",
    price: "100000",
    transmission: "Automatic",
    fuel_type: "Petrol",
    status: "In Stock",
    img: "/Tayota.webp",
  },
  {
    id: 2,
    name: "MINI Convertible",
    model: "2020",
    price: "10000",
    transmission: "Electric",
    fuel_type: "Battery",
    status: "In Stock",
    img: "/cooper.webp",
  },
  {
    id: 3,
    name: "Jaguar X4",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Diesel",
    status: "In Stock",
    img: "/Jaguar.webp",
  },
  {
    id: 4,
    name: "Mercedes-Benz A Class",
    model: "2021",
    price: "1000000",
    transmission: "Electric",
    fuel_type: "Battery",
    status: "In Stock",
    img: "/Mercedes-Benz.webp",
  },
  {
    id: 5,
    name: "Audi A5",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Petrol",
    status: "Reserved",
    img: "/Audi q7.webp",
  },
  {
    id: 6,
    name: "Audi A4",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Petrol",
    status: "Reserved",
    img: "/audi-A4.webp",
  },
  {
    id: 7,
    name: "Audi Q7",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Petrol",
    status: "Reserved",
    img: "/Audi q7.webp",
  },
  {
    id: 8,
    name: "Land Rover Range Rove",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Diesel",
    status: "Advertising",
    img: "/land rover.webp",
  },
  {
    id: 9,
    name: "Range Rove",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Diesel",
    status: "Advertising",
    img: "/",
  },
  {
    id: 10,
    name: "Maruati Suzuki",
    model: "2021",
    price: "1000000",
    transmission: "Manual",
    fuel_type: "Petrol",
    status: "For Sale",
    img: "",
  },
  {
    id: 11,
    name: "Maruati Suzuki Alto 800",
    model: "2021",
    price: "1000000",
    status: "For Sale",
    img: "",
  },
  {
    id: 12,
    name: "BALENO",
    model: "2021",
    price: "1000000",
    status: "For Sale",
    img: "",
  },
  {
    id: 13,
    name: "Tayota",
    model: "Fortuiner",
    price: "100000",
    transmission: "Automatic",
    fuel_type: "Petrol",
    status: "In Stock",
    img: "/Tayota.webp",
  },
  {
    id: 14,
    name: "MINI Convertible",
    model: "2020",
    price: "10000",
    transmission: "Electric",
    fuel_type: "Battery",
    status: "In Stock",
    img: "/cooper.webp",
  },
  {
    id: 15,
    name: "Jaguar X4",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Diesel",
    status: "In Stock",
    img: "/Jaguar.webp",
  },
  {
    id: 16,
    name: "Mercedes-Benz A Class",
    model: "2021",
    price: "1000000",
    transmission: "Electric",
    fuel_type: "Battery",
    status: "In Stock",
    img: "/Mercedes-Benz.webp",
  },
  {
    id: 17,
    name: "Audi A5",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Petrol",
    status: "Reserved",
    img: "/Audi q7.webp",
  },
  {
    id: 18,
    name: "Audi A4",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Petrol",
    status: "Reserved",
    img: "/audi-A4.webp",
  },
  {
    id: 19,
    name: "Audi Q7",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Petrol",
    status: "Reserved",
    img: "/Audi q7.webp",
  },
  {
    id: 20,
    name: "Land Rover Range Rove",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Diesel",
    status: "Advertising",
    img: "/land rover.webp",
  },
  {
    id: 21,
    name: "Range Rove",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Diesel",
    status: "Advertising",
    img: "/",
  },
  {
    id: 22,
    name: "Maruati Suzuki",
    model: "2021",
    price: "1000000",
    transmission: "Manual",
    fuel_type: "Petrol",
    status: "For Sale",
    img: "",
  },
  {
    id: 23,
    name: "Maruati Suzuki Alto 800",
    model: "2021",
    price: "1000000",
    status: "For Sale",
    img: "",
  },
  {
    id: 24,
    name: "Baleno",
    model: "2021",
    price: "1000000",
    status: "For Sale",
    img: "",
  },
];
