export default [
  {
    id: 1,
    brand: "Tayota",
    model: "Fortuiner",
    price: "100000",
    transmission: "Automatic",
    fuel_type: "Petrol",
    status: "In Stock",
    images: "/Tayota.webp",
    year: "2023",
  },
  {
    id: 2,
    brand: "MINI Convertible",
    model: "mini",
    price: "10000",
    transmission: "Electric",
    fuel_type: "Battery",
    status: "In Stock",
    images: "/cooper.webp",
    year: "2023",
  },
  {
    id: 3,
    brand: "Jaguar ",
    model: "X4",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Diesel",
    status: "In Stock",
    images: "/Jaguar.webp",
    year: "2023",
  },
  {
    id: 4,
    brand: "Mercedes-Benz ",
    model: "A Class",
    price: "1000000",
    transmission: "Electric",
    fuel_type: "Battery",
    status: "In Stock",
    images: "/Mercedes-Benz.webp",
    year: "2023",
  },
  {
    id: 5,
    brand: "Audi ",
    model: "A5",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Petrol",
    status: "Reserved",
    images: "/Audi q7.webp",
    year: "2023",
  },
  {
    id: 6,
    brand: "Audi ",
    model: "A5",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Petrol",
    status: "Reserved",
    images: "/audi-A4.webp",
    year: "2023",
  },
  {
    id: 7,
    brand: "Audi ",
    model: "Q7",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Petrol",
    status: "Reserved",
    images: "/Audi q7.webp",
    year: "2023",
  },
  {
    id: 8,
    brand: "Land Rover ",
    model: "Range Rove",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Diesel",
    status: "Advertising",
    images: "/land rover.webp",
    year: "2023",
  },
  {
    id: 9,
    brand: "Range Rove",
    model: "Range Rove",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Diesel",
    status: "Advertising",
    images: "/",
    year: "2023",
  },
  {
    id: 10,
    brand: "Maruati Suzuki",
    model: "Alto k10",
    price: "1000000",
    transmission: "Manual",
    fuel_type: "Petrol",
    status: "For Sale",
    images: "/",
    year: "2023",
  },
  {
    id: 11,
    brand: "Maruati Suzuki ",
    model: "Alto 800",
    price: "1000000",
    status: "For Sale",
    images: "/",
    year: "2023",
  },
  {
    id: 12,
    brand: "Maruati Suzuki",
    model: "Baleno",
    price: "1000000",
    status: "For Sale",
    images: "",
    year: "2023",
  },
  {
    id: 13,
    brand: "Tayota",
    model: "Fortuiner",
    price: "100000",
    transmission: "Automatic",
    fuel_type: "Petrol",
    status: "In Stock",
    images: "/Tayota.webp",
    year: "2023",
  },
  {
    id: 14,
    brand: "MINI Convertible",
    model: "2020",
    price: "10000",
    transmission: "Electric",
    fuel_type: "Battery",
    status: "In Stock",
    images: "/cooper.webp",
    year: "2023",
  },
  {
    id: 15,
    brand: "Jaguar X4",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Diesel",
    status: "In Stock",
    images: "/Jaguar.webp",
    year: "2023",
  },
  {
    id: 16,
    brand: "Mercedes-Benz A Class",
    model: "2021",
    price: "1000000",
    transmission: "Electric",
    fuel_type: "Battery",
    status: "In Stock",
    images: "/Mercedes-Benz.webp",
    year: "2023",
  },
  {
    id: 17,
    brand: "Audi A5",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Petrol",
    status: "Reserved",
    images: "/Audi q7.webp",
    year: "2023",
  },
  {
    id: 18,
    brand: "Audi A4",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Petrol",
    status: "Reserved",
    images: "/audi-A4.webp",
    year: "2023",
  },
  {
    id: 19,
    brand: "Audi Q7",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Petrol",
    status: "Reserved",
    images: "/Audi q7.webp",
    year: "2023",
  },
  {
    id: 20,
    brand: "Land Rover Range Rove",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Diesel",
    status: "Advertising",
    img: "/land rover.webp",
    year: "2023",
  },
  {
    id: 21,
    brand: "Range Rove",
    model: "2021",
    price: "1000000",
    transmission: "Automatic",
    fuel_type: "Diesel",
    status: "Advertising",
    images: "/",
    year: "2023",
  },
  {
    id: 22,
    brand: "Maruati Suzuki",
    model: "2021",
    price: "1000000",
    transmission: "Manual",
    fuel_type: "Petrol",
    status: "For Sale",
    images: "",
    year: "2023",
  },
  {
    id: 23,
    brand: "Maruati Suzuki Alto 800",
    model: "2021",
    price: "1000000",
    status: "For Sale",
    images: "",
    year: "2023",
  },
  {
    id: 24,
    brand: "Baleno",
    model: "2021",
    price: "1000000",
    status: "For Sale",
    images: "",
    year: "2023",
  },
];
